/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liang_myapplication_KeyBoard */

#ifndef _Included_myapplication_KeyBoard
#define _Included_myapplication_KeyBoard

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liang_myapplication_KeyBoard
 * Method:    Start_KeyBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1keyboard_1listen_KeyBoard_Start_1KeyBoard(JNIEnv *, jobject, jstring);
JNIEXPORT jstring JNICALL Java_android_1keyboard_1listen_KeyBoard_Get_1Input(JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_android_1keyboard_1listen_KeyBoard_Start_1KeyBoard3(JNIEnv *env, jobject , jstring );
JNIEXPORT jstring JNICALL Java_android_1keyboard_1listen_KeyBoard_Get_1Input3(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_android_1keyboard_1listen_KeyBoard_Start_1KeyBoard4(JNIEnv *env, jobject , jstring );
JNIEXPORT jstring JNICALL Java_android_1keyboard_1listen_KeyBoard_Get_1Input4(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
