#BNF+IAT 1.0 UTF-8;
!grammar wake;
!slot <callCmd>;
!slot <contact>;
!start <callStart>;
<callStart>:<callCmd>[<callName>][<callName2>];
<callCmd>:打开|关闭;
<callName>:客厅|门口|卧室|主卧|侧卧|客卧|阳台;
<callName2>:灯;